### ISSUE TITLE
No images being display on mobile

### ISSUE THREAD

**Issue by LudoProgramIt** [falaeco/DCART-WEB#51]
My phone is a LG G3 and when I look at the website from my phone no images are being displayed. The video from the first page is working tho.

**Comment by davidrawalia** [comment]
Are you viewing on in-finite.ca/secret? Are there any images in the project section or in the individual project pages? Can you post screenshots?

**Comment by LudoProgramIt** [comment]
![Capture+_2020-04-24-09-28-19](https://user-images.githubusercontent.com/18315267/80217600-f917ba00-860d-11ea-8634-8411ef8f4687.png)

**Comment by LudoProgramIt** [comment]
![Capture+_2020-04-24-09-28-07](https://user-images.githubusercontent.com/18315267/80217613-ff0d9b00-860d-11ea-968f-a745f9e4de03.png)

**Comment by LudoProgramIt** [comment]
As you can see, I see no images whatsoever from all the pages

**Comment by LudoProgramIt** [comment]
![Capture d’écran 2020-04-24 à 09 38 57 (2)](https://user-images.githubusercontent.com/18315267/80218667-798aea80-860f-11ea-8680-84aa222774ee.png)
On the computer I see the images in individual projects, but not on the project page, is it normal?

**Comment by davidrawalia** [comment]
Noted, should be fixed now... permissions issue when re-uploaded. You may need to do a hard refresh. If fixed, please close issue.

**Comment by nickph7** [comment]
It works for me 
![C1087451-FB72-4F3A-9E7B-72920D0D6EB2](https://user-images.githubusercontent.com/32775723/80219305-4432cc80-8610-11ea-9270-84520a8e12fa.png)
