### ISSUE TITLE
Button make a donation is not working

### ISSUE THREAD

**Issue by LudoProgramIt** [falaeco/DCART-WEB#53]
The button make a donation under the honorific mention of Valerie is just plain text and should be a link to where they can make a donation

**Comment by davidrawalia** [comment]
The link is right below it. Do you think it should extent to both lines?

**Comment by LudoProgramIt** [comment]
Yeah that would be great ! It is not intuitive to have to click on the name instead of the sentence make a donation!

**Comment by markusspecogna** [comment]
link runs on both lines now.
