### ISSUE TITLE
Can't fill the information under the stream pop-up cause of display issues

### ISSUE THREAD

**Issue by LudoProgramIt** [falaeco/DCART-WEB#56]
![Capture d’écran 2020-04-24 à 09 41 13 (2)](https://user-images.githubusercontent.com/18315267/80218947-dab2be00-860f-11ea-8b33-3558bdd400d1.png)
I can't scroll down to see more

**Comment by LudoProgramIt** [comment]
If I go fullscreen it's working
So it's a thing about the size of my page I guess

**Comment by LudoProgramIt** [comment]
![Capture d’écran 2020-04-24 à 09 43 28 (2)](https://user-images.githubusercontent.com/18315267/80219136-164d8800-8610-11ea-8824-be5078df583a.png)

**Comment by LudoProgramIt** [comment]
Actually, after playing a bit more with it, when it is being loaded for the first time, it does not display properly. However, the moment I adjust the size of my screen (does not matter if smaller or bigger) it adjust properly.

**Comment by davidrawalia** [comment]
![80214609-2746cb00-8609-11ea-8875-accf7da1863b](https://user-images.githubusercontent.com/22305787/80221319-1a2ed980-8613-11ea-9a86-04905a885417.jpg)
